### ISSUE TITLE
Recent changes have broken v2 camera motion detection functions... causes build failure.

### ISSUE THREAD

**Issue by LucidEye** [btsimonh/TasmotaBerryPLay#5]
It seems that some recent changes to the jpeg handler and some other libraries/dependencies have broken the v2 camera motion-detection features for ESP32-S3 devices.
I am trying to do a custom build so I can try testing the in-camera motion-detection and timelapse-record to SD card features, which would be extremely useful to me.
Here are my build flags for the camera in user_config_override....
```
USE_ESP32_WDT
USE_BERRY
USE_WEBCAM
USE_WEBCAM_V2
USE_WEBCAM_MOTION
UFILESYS_STATIC_SERVING
ENABLE_RTSPSERVER
USE_SPI
USE_SDCARD
USE_I2C
USE_WS2812
USE_BERRY_CAM
USE_BERRY_IMAGE
```

In VSCode, when trying to build using latest Tasmota Development 15.2.0.4 and `tasmota32s3-qio_opi-all` build environment, the build fails with the following errors...
```
Compiling .pio/build/tasmota32s3-qio_opi-all/src/tasmota.ino.cpp.o
/home/lucid/Documents/PlatformIO/Projects/Tasmota-development_15.2.0.4/tasmota/tasmota_xdrv_driver/xdrv_50_filesystem.ino:1130:10: error: 'bool StaticRequestHandlerAuth::handle(WebServer&, HTTPMethod, String)' marked 'override', but does not override
 1130 |     bool handle(WebServer& server, HTTPMethod requestMethod, String requestUri) override {
      |          ^~~~~~
/home/lucid/Documents/PlatformIO/Projects/Tasmota-development_15.2.0.4/tasmota/tasmota_xdrv_driver/xdrv_81_esp32_webcam_task_motion.ino: In function 'bool wc_jpg2mono(const uint8_t*, size_t, PICSTORE*, int)':
/home/lucid/Documents/PlatformIO/Projects/Tasmota-development_15.2.0.4/tasmota/tasmota_xdrv_driver/xdrv_81_esp32_webcam_task_motion.ino:523:33: error: 'jpg_scale_t' was not declared in this scope; did you mean 'lv_scale_t'?
  523 |     if(esp_jpg_decode(src_len, (jpg_scale_t)scale, wc_jpg_read, _mono_write, (void*)&jpeg) != ESP_OK){
      |                                 ^~~~~~~~~~~
      |                                 lv_scale_t
/home/lucid/Documents/PlatformIO/Projects/Tasmota-development_15.2.0.4/tasmota/tasmota_xdrv_driver/xdrv_81_esp32_webcam_task_motion.ino:523:8: error: 'esp_jpg_decode' was not declared in this scope; did you mean 'esp_jpeg_decode'?
  523 |     if(esp_jpg_decode(src_len, (jpg_scale_t)scale, wc_jpg_read, _mono_write, (void*)&jpeg) != ESP_OK){
      |        ^~~~~~~~~~~~~~
      |        esp_jpeg_decode
*** [.pio/build/tasmota32s3-qio_opi-all/src/tasmota.ino.cpp.o] Error 1
Compiling .pio/build/tasmota32s3-qio_opi-all/lib454/WiFiHelper/WiFiHelper_ESP32.cpp.o
```

I have isolated these build flags as the ones calling to the file `xdrv_50_filesystem.ino` and causing the build failures...
```
USE_WEBCAM_MOTION
UFILESYS_STATIC_SERVING
```
If I omit these 2 flags, the build compiles successfully and flashes & runs on my device.

This is the device I'm using...

![Image](https://github.com/user-attachments/assets/1f56bb81-7435-4a47-8539-51408503fb40)

Hardware template:
```
{"NAME":"ESP32-S3-CAM","GPIO":[1,1,0,1,5024,5056,5120,5152,5090,5089,5091,5088,5092,5184,1,4992,5095,5094,5093,0,0,0,0,0,0,0,0,8800,8832,8864,0,0,544,0,1,1,0,1376],"FLAG":0,"BASE":1}
```

<img width="229" height="898" alt="Image" src="https://github.com/user-attachments/assets/1f727fd3-e45c-4ad6-b125-429bad7826eb" />
